site_name: Leandro Melloni Valle
site_url: https://leandro-melloni.github.io/
site_author: Leandro Melloni Valle

#repo_url: https://github.com/leandro-melloni/leandro-melloni.gihub.io
#repo_name: leandro-melloni.github.io

copyright: Copyright &copy; 2023 Leandro Melloni Valle


theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      primary: green
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      primary: green
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: green
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.tabs
    - navigation.path
    - navigation.instant
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - search.suggest
    - content.tooltips
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
  favicon: assets/logo.png
  logo: assets/logo.png

extra:
  annotate:
    json: [.s2] 
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/leandro-melloni
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/leandro-melloni-valle-78100335/

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true


plugins: 
  - search:
      lang:
        - pt
        - en
  - monorepo
  - codeinclude
  - awesome-pages
  - autolinks
  - rss
  - blog
  - glightbox
    

nav:
  - Home: index.md
  - Artigos:
    - Artigos: blog/index.md
    - "Github Actions":
      - "Entendendo um pouco sobre Workflows!": blog/github-actions/workflows.md
  - "Quem sou eu": about.md

#extra_css:
#  - assets/css/extra.css

extra_javascript:
#  - assets/js/marked.min.js
  - assets/js/extra.js