site_name: Leandro Melloni Valle
site_url: https://leandro-melloni.github.io/

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.tabs
    - navigation.path
    - navigation.instant
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - search.suggest
    - content.tooltips
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy


markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.tabbed:
      alternate_style: true
  


plugins: 
  - search:
      lang:
        - pt
        - en
  - monorepo
  - codeinclude
  - awesome-pages
  - autolinks
  - rss
  - blog
    

nav:
  - Home: index.md
  - Artigos:
    - Artigos: blog/index.md
  - About: 
      - about.md

#extra_css:
#  - assets/css/extra.css

extra_javascript:
#  - assets/js/marked.min.js
  - assets/js/extra.js